### ISSUE TITLE
členství klubu jako member of, ne v rámci position held

### ISSUE THREAD

**Issue by kokes** [kokes/wikidata-politici#26]
[Okamura](https://www.wikidata.org/wiki/Q2223090) byl zvolen a založili si poslanecký klub pro SPD. My mu přiřazujem klub do position held poslanec.

Jenže pak je [Klaus mladší](https://www.wikidata.org/wiki/Q6434601), který už není v klubu, ve kterém začínal, nyní je nezařazený. Ale poslancem dál je.

Navrhuju tedy změnit rozvržení dat, že časově měnné propriety (v tom případě jen klub) bych vyčlenil z position held poslanec a přehodil bych je do member of: klub (a v případě předsednictví klubu bych přidal ještě position held: chairman klubu).

Je tam ještě další problém, že je rozdíl mezi stranou a klubem (https://github.com/kokes/wikidata-politici/issues/24), ale to vyřešíme bokem.

Co myslíš, @vojtechdostal?

**Comment by kokes** [comment]
+ tohle by mělo jít dobře načíst z psp.cz dat

**Comment by VojtechDostal** [comment]
Důrazně bych rozlišoval mezi stranickou příslušností, funkcemi (ve funkci) a členstvím v poslaneckých klubech (člen čeho). Jak správně ukazuješ na příkladech, ty věci spolu zas tak nesouvisí. U všeho důrazně uvádět s vymezeními od,do :-) Je pravda že "frakce" bývá uváděna jako vymezení u funkcí a taky mi to připadá nešťastné. Tady jsou všichni čeští poslanci, kteří toto vymezení používají!: https://w.wiki/EDS . Kdybys potřeboval s Query Servisem pomoct, řekni.

**Comment by VojtechDostal** [comment]
Pro jistotu bych ty frakce probral s lidmi na Facebooku, Ben Skála a Petr Kadlec se politice relativně věnují, tak na to budou mít názor ;)

**Comment by kokes** [comment]
Nakonec se mi tam nezdálo víc věcí, shrnul jsem je na FB

https://www.facebook.com/groups/151013568681003/permalink/813845002397853/

Čau, procházel jsem poslance a všiml si pár věcí v tom datovém modelu, které se mi úplně nezdají. Snad toho neni moc najednou, jen se mi tam nezdálo víc věcí.

1) Často mají v rámci poslancování vyplněnou parliamentary group (P4100), přitom to není věc spojená s tím zvolením, protože se může v čase změnit. (Např. opustit klub a stát se nezařazeným.) Navíc v současné podobě mají parliamentary group vyplněnou stranu (přímo v té pozici) - jenže strana a klub jsou dvě dost rozdílné věci. Navrhoval bych tedy přiřadit parliamentary group jako top level property, přidat tam started/ended atd. (viz třeba Renzi Q47563) A ta groupa by byla fakt poslaneckej klub, ne strana jako teď.

2) Předsednictví v klubech bych dělal přes position held. (Vadí, že členství by byla P4100, ale předsednictví P31?)

3) Docela mě překvapuje, že české poslanecké kluby mají vlastní instanci, která není subclassou parliamentary group (Q848197), nýbrž jdou cestou political faction (Q1393724). Je to tak OK?

4) Vidím i elected in (P2715) i parliamentary term (P2937) - jedno ale implikuje druhé, je to vlastně 100% overlap co se týče významu. Žádné by-elections u nás v PSP nejsou, maximálně někdo může být povýšen z náhradníka na poslance, stále byl ale zvolen v těch volbách. Nemůžem tedy jednu z těchto dvou properties nepoužívat?

5) Občas vidím vyplněné member of, kde je hodnota toho parliamentary term, který jsem zmiňoval výše (viz např. Q15249537). Máme tak stejnou informaci třikrát - nešlo by se shodnout na jedné jediné reprezentaci poslance v daném funkčním období? (Navíc UI Wikidat se mi stěžuje, že parlamentní období neni úplně sdružení lidí.)

---

Těžké otázky... nikomu se nechce do jejich zodpovídání a nikdo s touto oblastí moc nemá zkušenosti :) laicky 1, 2 souhlasím, 3 netuším zda poslanecký klub je spíš political faction nebo parliamentary group (to je otázka pro politologa), 4 souhlas že je to zbytečné, ale zas to ničemu nevadí a pokud v některých státech není 100% překryv, tak to je obojí cenná informace, 5 to vypadá jako totální nesmysl, odstraňovat či ještě lépe přesouvat tam, kde to smysl dává.

---

1) Rozlišovat v P39 poslanecký klub (P4100) a stranu (P1628) je určitě dobré, ale v minulosti nějak chyběly ty klubové položky. Nápad s P4100 jako top level property vypadá hodně zajímavě.
2) ano, dobrý nápad.
3) Asi je to jedno, klidně přidat i Q848197.
4) Nechal bych obojí, ničemu to podle mého nevadí.
5) To je nějaký starý pozůstatek, možno s klidem mazat.

**Comment by kokes** [comment]
Čau, procházel jsem poslance a všiml si pár věcí v tom datovém modelu, které se mi úplně nezdají. Snad toho neni moc najednou, jen se mi tam nezdálo víc věcí.

1) Často mají v rámci poslancování vyplněnou parliamentary group (P4100), přitom to není věc spojená s tím zvolením, protože se může v čase změnit. (Např. opustit klub a stát se nezařazeným.) Navíc v současné podobě mají parliamentary group vyplněnou stranu (přímo v té pozici) - jenže strana a klub jsou dvě dost rozdílné věci. Navrhoval bych tedy přiřadit parliamentary group jako top level property, přidat tam started/ended atd. (viz třeba Renzi Q47563) A ta groupa by byla fakt poslaneckej klub, ne strana jako teď.

2) Předsednictví v klubech bych dělal přes position held. (Vadí, že členství by byla P4100, ale předsednictví P31?)

3) Docela mě překvapuje, že české poslanecké kluby mají vlastní instanci, která není subclassou parliamentary group (Q848197), nýbrž jdou cestou political faction (Q1393724). Je to tak OK?

4) Vidím i elected in (P2715) i parliamentary term (P2937) - jedno ale implikuje druhé, je to vlastně 100% overlap co se týče významu. Žádné by-elections u nás v PSP nejsou, maximálně někdo může být povýšen z náhradníka na poslance, stále byl ale zvolen v těch volbách. Nemůžem tedy jednu z těchto dvou properties nepoužívat?

5) Občas vidím vyplněné member of, kde je hodnota toho parliamentary term, který jsem zmiňoval výše (viz např. Q15249537). Máme tak stejnou informaci třikrát - nešlo by se shodnout na jedné jediné reprezentaci poslance v daném funkčním období? (Navíc UI Wikidat se mi stěžuje, že parlamentní období neni úplně sdružení lidí.)

---

Těžké otázky... nikomu se nechce do jejich zodpovídání a nikdo s touto oblastí moc nemá zkušenosti :) laicky 1, 2 souhlasím, 3 netuším zda poslanecký klub je spíš political faction nebo parliamentary group (to je otázka pro politologa), 4 souhlas že je to zbytečné, ale zas to ničemu nevadí a pokud v některých státech není 100% překryv, tak to je obojí cenná informace, 5 to vypadá jako totální nesmysl, odstraňovat či ještě lépe přesouvat tam, kde to smysl dává.

---

1) Rozlišovat v P39 poslanecký klub (P4100) a stranu (P1628) je určitě dobré, ale v minulosti nějak chyběly ty klubové položky. Nápad s P4100 jako top level property vypadá hodně zajímavě.
2) ano, dobrý nápad.
3) Asi je to jedno, klidně přidat i Q848197.
4) Nechal bych obojí, ničemu to podle mého nevadí.
5) To je nějaký starý pozůstatek, možno s klidem mazat.

**Comment by kokes** [comment]
Členství v klubech bude nějak takto. Budu muset dozakládat pár klubů, ale většina už entitu má.

```sql
SELECT
	v_ids.wikidata_id, v_ids.psp_id, jmeno, prijmeni, zkratka, nazev_organu_cz, od, do
FROM
	v_poslanci_organy org
	inner join v_ids on org.id_osoba = v_ids.psp_id
	where nazev_organu_cz like 'Poslanecký klub%' --and prijmeni ='Okamura'
	order by wikidata_id, od
LIMIT 10000;
```

**Comment by kokes** [comment]
Mám připraveno 1828 členství v klubech, vlastně ve všech za existenci Česka. Už jen zařídim entitu databáze PSP, abych mohl zdrojovat, a jdu přidávat.

![Screen Shot 2020-01-11 at 00 42 49](https://user-images.githubusercontent.com/8451755/72193798-57c47980-340b-11ea-9ad1-1aa005a7c861.png)

**Comment by kokes** [comment]
Tak členství v klubech bychom měli, ještě přidat (místo)předsednictví

**Comment by kokes** [comment]
předsednictva budou tady - bacha na revizory a členy vedení, vše ostatní je ale jen nějaký jiný opis (místo)předsedy

```
SELECT
	v_ids.wikidata_id, v_ids.psp_id,
	jmeno, prijmeni,
	zkratka, nazev_funkce_cz,
	(case when nazev_funkce_cz like '%místopředseda%' then 'místopředseda'
		when nazev_funkce_cz like '%mistopredseda%' then 'místopředseda'
		when nazev_funkce_cz like '%předseda%' then 'předseda'
		else null end) as funkce,	
	nazev_organu_cz, od_o, do_o
FROM
	v_poslanci_funkce fun
	inner join v_ids on fun.id_osoba = v_ids.psp_id
	where nazev_organu_cz like 'Poslanecký klub%' --and prijmeni ='Okamura'
			and (nazev_funkce_cz like '%předseda%'
						or nazev_funkce_cz like '%místopředseda%'
						or nazev_funkce_cz like '%mistopredseda%')
	order by wikidata_id, od_o
LIMIT 10000;
```

**Comment by kokes** [comment]
předsednictvo přidaný - neřešil jsem jen první/druhý/... místopředsedy, protože jsme nějak nedovymysleli, jak to dobře udělat (aniž bychom přidávali další a další entity)
